enum MAZE_ALGORITHM_RENDER_BASE_GRID_TYPES {
  BORDERED = 'BORDERED',
  CARVED = 'CARVED',
}

enum MAZE_ALGORITHM_TYPES {
  ELLER,
  RECURSIVE_DIVISION,
  GROWING_TREE,
  KRUSKAL,
  HUNT_AND_KILL,
  SIDEWINDER,
  BINARY_TREE,
  WILSONS,
}

const ALGORITHM:any = { _BASE: MAZE_ALGORITHM_RENDER_BASE_GRID_TYPES, }
for(let mAT in MAZE_ALGORITHM_TYPES) {
  if(mAT.length > 1)ALGORITHM[mAT] = mAT
}

export const MAZE_ALGORITHM = ALGORITHM