language: node_js
sudo: false
matrix:
  include:
    - node_js: "13"
      install:
        - "mv node_modules/.cache . || true"
        - "npm ci"
        - "mv .cache node_modules/ || true"
      script:
        - "npm t"
    - node_js: "12"
    - node_js: "11"
    - node_js: "10"
    - node_js: "8"
cache:
  directories:
  - node_modules/.cache
  - ~/.npm
script:
  - "tap -J test/*.js test/toml-stream/*.js"
